declare function _default(__exports: any): {
    newJSVal: (v: any) => number;
    getJSVal: (k: any) => any;
    freeJSVal: (k: any) => void;
    scheduleWork: () => any;
    ZC1ZCtinyaplzm0zi12zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => (...args: any[]) => any;
    ZC3ZCtinyaplzm0zi12zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => (...args: any[]) => any;
    ZC8ZCtinyaplzm0zi12zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any, $2: any, $3: any, $4: any) => Promise<any>;
    ZC9ZCtinyaplzm0zi12zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any, $2: any, $3: any) => Promise<any>;
    ZC10ZCtinyaplzm0zi12zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any, $2: any) => Promise<any>;
    ZC11ZCtinyaplzm0zi12zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => Promise<any>;
    ZC12ZCtinyaplzm0zi12zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any, $2: any) => boolean;
    ZC13ZCtinyaplzm0zi12zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any, $2: any) => any;
    ZC14ZCtinyaplzm0zi12zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => $1 is any[];
    ZC15ZCtinyaplzm0zi12zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => "string" | "number" | "bigint" | "boolean" | "symbol" | "undefined" | "object" | "function";
    ZC16ZCtinyaplzm0zi12zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => {
        [k: string]: any;
    };
    ZC17ZCtinyaplzm0zi12zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => [string, any][];
    ZC18ZCtinyaplzm0zi12zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => any;
    ZC19ZCtinyaplzm0zi12zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => any;
    ZC20ZCtinyaplzm0zi12zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any, $2: any) => any[];
    ZC23ZCtinyaplzm0zi12zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => any;
    ZC24ZCtinyaplzm0zi12zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => any;
    ZC25ZCtinyaplzm0zi12zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => any;
    ZC26ZCtinyaplzm0zi12zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => any;
    ZC27ZCtinyaplzm0zi12zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => boolean;
    ZC28ZCtinyaplzm0zi12zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: () => undefined;
    ZC30ZCtinyaplzm0zi12zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any, $2: any) => any;
    ZC31ZCtinyaplzm0zi12zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any, $2: any) => any;
    ZC32ZCtinyaplzm0zi12zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => any;
    ZC36ZCtinyaplzm0zi12zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => never[];
    ZC37ZCtinyaplzm0zi12zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => any;
    ZC38ZCtinyaplzm0zi12zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => any;
    ZC39ZCtinyaplzm0zi12zi0zi0zminplacezmtinyaplzmjsZCMainZC: ($1: any, $2: any) => Promise<void>;
    ZC40ZCtinyaplzm0zi12zi0zi0zminplacezmtinyaplzmjsZCMainZC: ($1: any) => Promise<any>;
    ZC41ZCtinyaplzm0zi12zi0zi0zminplacezmtinyaplzmjsZCMainZC: ($1: any) => Promise<string>;
    ZC0ZCghczminternalZCGHCziInternalziWasmziPrimziExportsZC: ($1: any, $2: any) => any;
    ZC16ZCghczminternalZCGHCziInternalziWasmziPrimziExportsZC: ($1: any, $2: any) => any;
    ZC18ZCghczminternalZCGHCziInternalziWasmziPrimziExportsZC: ($1: any, $2: any) => any;
    ZC19ZCghczminternalZCGHCziInternalziWasmziPrimziExportsZC: ($1: any) => any;
    ZC20ZCghczminternalZCGHCziInternalziWasmziPrimziExportsZC: ($1: any) => void;
    ZC21ZCghczminternalZCGHCziInternalziWasmziPrimziExportsZC: ($1: any, $2: any) => void;
    ZC22ZCghczminternalZCGHCziInternalziWasmziPrimziExportsZC: () => Promise<any>;
    ZC23ZCghczminternalZCGHCziInternalziWasmziPrimziExportsZC: ($1: any, $2: any) => void;
    ZC17ZCghczminternalZCGHCziInternalziWasmziPrimziImportsZC: ($1: any, $2: any) => any;
    ZC18ZCghczminternalZCGHCziInternalziWasmziPrimziImportsZC: ($1: any, $2: any) => any;
    ZC0ZCghczminternalZCGHCziInternalziWasmziPrimziTypesZC: ($1: any) => string;
    ZC1ZCghczminternalZCGHCziInternalziWasmziPrimziTypesZC: ($1: any, $2: any) => string;
    ZC2ZCghczminternalZCGHCziInternalziWasmziPrimziTypesZC: ($1: any, $2: any, $3: any) => number;
    ZC3ZCghczminternalZCGHCziInternalziWasmziPrimziTypesZC: ($1: any) => any;
    ZC4ZCghczminternalZCGHCziInternalziWasmziPrimziTypesZC: ($1: any) => void;
    ZC0ZCghczminternalZCGHCziInternalziWasmziPrimziConcziInternalZC: ($1: any) => Promise<any>;
};
export default _default;
