declare function _default(__exports: any): {
    newJSVal: (v: any) => number;
    getJSVal: (k: any) => any;
    freeJSVal: (k: any) => void;
    scheduleWork: () => any;
    ZC1ZCtinyaplzm0zi6zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => (a1: any, a2: any) => any;
    ZC3ZCtinyaplzm0zi6zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => (a1: any) => any;
    ZC6ZCtinyaplzm0zi6zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any, $2: any, $3: any) => Promise<any>;
    ZC7ZCtinyaplzm0zi6zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any, $2: any) => Promise<any>;
    ZC8ZCtinyaplzm0zi6zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => Promise<any>;
    ZC9ZCtinyaplzm0zi6zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any, $2: any) => boolean;
    ZC10ZCtinyaplzm0zi6zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any, $2: any) => any;
    ZC11ZCtinyaplzm0zi6zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => $1 is any[];
    ZC12ZCtinyaplzm0zi6zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => "string" | "number" | "bigint" | "boolean" | "symbol" | "undefined" | "object" | "function";
    ZC13ZCtinyaplzm0zi6zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => {
        [k: string]: any;
    };
    ZC14ZCtinyaplzm0zi6zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => [string, any][];
    ZC15ZCtinyaplzm0zi6zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => any;
    ZC16ZCtinyaplzm0zi6zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => any;
    ZC17ZCtinyaplzm0zi6zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any, $2: any) => any[];
    ZC20ZCtinyaplzm0zi6zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => any;
    ZC21ZCtinyaplzm0zi6zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => any;
    ZC22ZCtinyaplzm0zi6zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => any;
    ZC23ZCtinyaplzm0zi6zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => any;
    ZC24ZCtinyaplzm0zi6zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => boolean;
    ZC25ZCtinyaplzm0zi6zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: () => undefined;
    ZC27ZCtinyaplzm0zi6zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any, $2: any) => any;
    ZC28ZCtinyaplzm0zi6zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any, $2: any) => any;
    ZC29ZCtinyaplzm0zi6zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => any;
    ZC33ZCtinyaplzm0zi6zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => never[];
    ZC34ZCtinyaplzm0zi6zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => any;
    ZC35ZCtinyaplzm0zi6zi0zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => any;
    ZC38ZCtinyaplzm0zi6zi0zi0zminplacezmtinyaplzmjsZCMainZC: ($1: any, $2: any) => Promise<void>;
    ZC39ZCtinyaplzm0zi6zi0zi0zminplacezmtinyaplzmjsZCMainZC: ($1: any) => Promise<any>;
    ZC40ZCtinyaplzm0zi6zi0zi0zminplacezmtinyaplzmjsZCMainZC: ($1: any) => Promise<string>;
    ZC0ZCghczminternalZCGHCziInternalziWasmziPrimziExportsZC: ($1: any, $2: any) => any;
    ZC16ZCghczminternalZCGHCziInternalziWasmziPrimziExportsZC: ($1: any, $2: any) => any;
    ZC18ZCghczminternalZCGHCziInternalziWasmziPrimziExportsZC: ($1: any, $2: any) => any;
    ZC19ZCghczminternalZCGHCziInternalziWasmziPrimziExportsZC: ($1: any) => any;
    ZC20ZCghczminternalZCGHCziInternalziWasmziPrimziExportsZC: () => Promise<any>;
    ZC21ZCghczminternalZCGHCziInternalziWasmziPrimziExportsZC: ($1: any, $2: any) => void;
    ZC17ZCghczminternalZCGHCziInternalziWasmziPrimziImportsZC: ($1: any, $2: any) => any;
    ZC18ZCghczminternalZCGHCziInternalziWasmziPrimziImportsZC: ($1: any, $2: any) => any;
    ZC0ZCghczminternalZCGHCziInternalziWasmziPrimziTypesZC: ($1: any) => string;
    ZC1ZCghczminternalZCGHCziInternalziWasmziPrimziTypesZC: ($1: any, $2: any) => string;
    ZC2ZCghczminternalZCGHCziInternalziWasmziPrimziTypesZC: ($1: any, $2: any, $3: any) => number;
    ZC3ZCghczminternalZCGHCziInternalziWasmziPrimziTypesZC: ($1: any) => any;
    ZC4ZCghczminternalZCGHCziInternalziWasmziPrimziTypesZC: ($1: any) => void;
    ZC0ZCghczminternalZCGHCziInternalziWasmziPrimziConcziInternalZC: ($1: any) => Promise<any>;
};
export default _default;
