declare function _default(__exports: any): {
    newJSVal: (v: any) => number;
    getJSVal: (k: any) => any;
    freeJSVal: (k: any) => void;
    scheduleWork: () => any;
    ZC0ZCtinyaplzm0zi5zi1zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any, $2: any) => boolean;
    ZC1ZCtinyaplzm0zi5zi1zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any, $2: any) => any;
    ZC2ZCtinyaplzm0zi5zi1zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => $1 is any[];
    ZC3ZCtinyaplzm0zi5zi1zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => "string" | "number" | "bigint" | "boolean" | "symbol" | "undefined" | "object" | "function";
    ZC4ZCtinyaplzm0zi5zi1zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => {
        [k: string]: any;
    };
    ZC5ZCtinyaplzm0zi5zi1zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => [string, any][];
    ZC6ZCtinyaplzm0zi5zi1zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => any;
    ZC7ZCtinyaplzm0zi5zi1zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => any;
    ZC8ZCtinyaplzm0zi5zi1zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any, $2: any) => any[];
    ZC9ZCtinyaplzm0zi5zi1zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => any;
    ZC11ZCtinyaplzm0zi5zi1zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => any;
    ZC12ZCtinyaplzm0zi5zi1zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => any;
    ZC13ZCtinyaplzm0zi5zi1zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => any;
    ZC14ZCtinyaplzm0zi5zi1zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => any;
    ZC15ZCtinyaplzm0zi5zi1zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => boolean;
    ZC17ZCtinyaplzm0zi5zi1zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any, $2: any) => any;
    ZC18ZCtinyaplzm0zi5zi1zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any, $2: any) => any;
    ZC19ZCtinyaplzm0zi5zi1zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => any;
    ZC23ZCtinyaplzm0zi5zi1zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => never[];
    ZC24ZCtinyaplzm0zi5zi1zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => any;
    ZC25ZCtinyaplzm0zi5zi1zi0zminplacezmtinyaplzmjsZCJSBridgeZC: ($1: any) => any;
    ZC33ZCtinyaplzm0zi5zi1zi0zminplacezmtinyaplzmjsZCMainZC: ($1: any, $2: any, $3: any) => Promise<any>;
    ZC34ZCtinyaplzm0zi5zi1zi0zminplacezmtinyaplzmjsZCMainZC: ($1: any, $2: any) => Promise<any>;
    ZC35ZCtinyaplzm0zi5zi1zi0zminplacezmtinyaplzmjsZCMainZC: ($1: any, $2: any) => Promise<void>;
    ZC36ZCtinyaplzm0zi5zi1zi0zminplacezmtinyaplzmjsZCMainZC: ($1: any) => Promise<any>;
    ZC37ZCtinyaplzm0zi5zi1zi0zminplacezmtinyaplzmjsZCMainZC: ($1: any, $2: any) => Promise<void>;
    ZC38ZCtinyaplzm0zi5zi1zi0zminplacezmtinyaplzmjsZCMainZC: ($1: any) => Promise<any>;
    ZC39ZCtinyaplzm0zi5zi1zi0zminplacezmtinyaplzmjsZCMainZC: ($1: any) => any;
    ZC40ZCtinyaplzm0zi5zi1zi0zminplacezmtinyaplzmjsZCMainZC: ($1: any) => any;
    ZC0ZCghczminternalZCGHCziInternalziWasmziPrimziExportsZC: ($1: any, $2: any) => any;
    ZC16ZCghczminternalZCGHCziInternalziWasmziPrimziExportsZC: ($1: any, $2: any) => any;
    ZC18ZCghczminternalZCGHCziInternalziWasmziPrimziExportsZC: ($1: any, $2: any) => any;
    ZC19ZCghczminternalZCGHCziInternalziWasmziPrimziExportsZC: ($1: any) => any;
    ZC20ZCghczminternalZCGHCziInternalziWasmziPrimziExportsZC: () => Promise<any>;
    ZC17ZCghczminternalZCGHCziInternalziWasmziPrimziImportsZC: ($1: any, $2: any) => any;
    ZC18ZCghczminternalZCGHCziInternalziWasmziPrimziImportsZC: ($1: any, $2: any) => any;
    ZC0ZCghczminternalZCGHCziInternalziWasmziPrimziTypesZC: ($1: any) => string;
    ZC1ZCghczminternalZCGHCziInternalziWasmziPrimziTypesZC: ($1: any, $2: any) => string;
    ZC2ZCghczminternalZCGHCziInternalziWasmziPrimziTypesZC: ($1: any, $2: any, $3: any) => number;
    ZC3ZCghczminternalZCGHCziInternalziWasmziPrimziTypesZC: ($1: any) => any;
    ZC4ZCghczminternalZCGHCziInternalziWasmziPrimziTypesZC: ($1: any) => void;
    ZC0ZCghczminternalZCGHCziInternalziWasmziPrimziConcziInternalZC: ($1: any) => Promise<any>;
};
export default _default;
