name: Build
on:
  push:
    branches: beta
  pull_request:
    branches: beta

jobs:
  ubuntu:
    name: Ubuntu 20.04
    runs-on: ubuntu-20.04

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      
      - name: Setup GHC
        uses: haskell-actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: '9.10.1'

      - name: Freeze for cache key
        run: 'cabal freeze'
      
      - name: Cache
        uses: actions/cache@v4
        env:
          platform: ubuntu
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ env.platform }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ env.platform }}-
            
      - name: Build
        run: 'cabal build exe:tinyapl'

      - name: Prepare artifact
        run: 'cp $(cabal list-bin tinyapl | tail -n 1) ./tinyapl'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'tinyapl'
          path: './tinyapl'

  windows:
    name: Windows
    runs-on: windows-2022

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      
      - name: Setup GHC
        uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.10.1'

      - name: Cache
        uses: actions/cache@v4
        env:
          platform: windows
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ env.platform }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ env.platform }}-

      - name: Hack part 1
        run: 'powershell -Command "rm -Re -Fo ./dist-newstyle/src"'

      - name: Build
        run: 'cabal build exe:tinyapl'

      - name: Hack part 2
        run: 'powershell -Command "rm -Re -Fo ./dist-newstyle/src"'

      - name: Prepare artifact
        run: 'powershell -Command "cp $($(cabal list-bin tinyapl) -split "`n" | Select-Object -Last 1) ./tinyapl.exe"'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'tinyapl.exe'
          path: './tinyapl.exe'
