name: Build
on:
  push:
    branches: beta
  pull_request:
    branches: beta

jobs:
  ubuntu:
    name: Ubuntu 20.04
    runs-on: ubuntu-20.04

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      
      - name: Setup GHC
        uses: haskell-actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: '9.10.1'

      - name: Freeze for cache key
        run: 'cabal freeze'
      
      - name: Cache
        uses: actions/cache@v4
        env:
          platform: ubuntu
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ env.platform }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ env.platform }}-
            
      - name: Build
        run: 'cabal build exe:tinyapl'

      - name: Prepare artifact
        run: 'cp $(cabal list-bin tinyapl | tail -n 1) ./tinyapl'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'tinyapl'
          path: './tinyapl'

  windows:
    name: Windows
    runs-on: windows-2022

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Cache Haskell tooling
        uses: actions/cache@v4
        with:
          path: C:/ghcup/bin
          key: win-tooling-cache-${{ hashFiles('.github/workflows/build.yml') }} # no idea what to use for a better key LMAO
          restore-keys: |
            win-tooling-cache-
      
      - name: Setup GHC
        uses: haskell-actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: '9.10.1'

      - name: Hack part 0
        run: 'rm -rf ./dist-newstyle/src'
        shell: bash

      - name: Freeze for cache key
        run: 'cabal freeze'
        shell: bash

      - name: Cache
        uses: actions/cache@v4
        env:
          platform: windows
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ env.platform }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ env.platform }}-

      - name: Hack part 1
        run: 'rm -rf ./dist-newstyle/src'
        shell: bash

      - name: Build
        run: 'cabal build exe:tinyapl'
        shell: bash

      - name: Hack part 2
        run: 'rm -rf ./dist-newstyle/src'
        shell: bash

      - name: Prepare artifact
        run: 'cp $(cabal list-bin tinyapl | tail -n 1) ./tinyapl.exe'
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'tinyapl.exe'
          path: './tinyapl.exe'
